version: 2

updates:
  # Python
  - package-ecosystem: "uv"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "monthly"
    groups:
      python-dev-tools:
        dependency-type: "development"
        update-types: ["minor", "patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns: ["*"]
